name: Build and Test Code

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  Build:
    environment:
    runs-on: ubuntu-latest
    steps:
      - name: Pulling git repo
        uses: actions/checkout@v2

      - name: Update pip
        run: pip install --upgrade pip

      - name: Installing dependencies
        run: pip install -r requirements.txt

      - name: Testing with Pytest
        run: |
          pip install pytest
          pytest -v